apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: dotnet-basic-ctenksmv
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/sjmrhtap/dotnet-basic-ctenksmv:5851d47d48649f4e041bab24a2b8b4115b0bb73a
          name: container-image
